using LearnPlane.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace LearnPlane.Web.Data;

public static class DatabaseInitializer
{
    public static async Task InitializeAsync(IServiceProvider services, IConfiguration configuration)
    {
        await using var scope = services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<LearnPlaneDbContext>();
        await db.Database.EnsureCreatedAsync();
        await ApplyRewardStoreUpgradeAsync(db);

        var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();
        foreach (var role in new[] { Roles.Admin, Roles.Student })
        {
            if (!await roleManager.RoleExistsAsync(role))
                await roleManager.CreateAsync(new IdentityRole(role));
        }

        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        var admin = await userManager.FindByNameAsync("admin");
        if (admin is null)
        {
            admin = new ApplicationUser { UserName = "admin", DisplayName = "Administrator" };
            var password = configuration["ADMIN_INITIAL_PASSWORD"] ?? "3d9XehYf";
            var result = await userManager.CreateAsync(admin, password);
            if (!result.Succeeded)
                throw new InvalidOperationException($"Administrator kunne ikke opprettes: {string.Join(", ", result.Errors.Select(x => x.Description))}");
            await userManager.AddToRoleAsync(admin, Roles.Admin);
        }

        if (!await db.Courses.AnyAsync())
        {
            db.Courses.AddRange(CurriculumCatalog.CreateCourses());
            await db.SaveChangesAsync();
        }

        if (!await db.RewardItems.AnyAsync())
        {
            db.RewardItems.Add(new RewardItem
            {
                Name = "Leksefri-kupong",
                Description = "En hyggelig forhåndsvisning: Vis kupongen til en voksen og avtal en liten, leksefri bonusstund.",
                ImageUrl = "/images/reward-homework.svg",
                PricePoints = 50,
                IsActive = true
            });
            await db.SaveChangesAsync();
        }
    }

    private static async Task ApplyRewardStoreUpgradeAsync(LearnPlaneDbContext db)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "RewardItems" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(140) NOT NULL,
                "Description" character varying(600) NOT NULL,
                "ImageUrl" text NOT NULL,
                "PricePoints" integer NOT NULL,
                "IsActive" boolean NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                "UpdatedAtUtc" timestamp with time zone NOT NULL
            );
            CREATE TABLE IF NOT EXISTS "CartItems" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" text NOT NULL,
                "RewardItemId" integer NOT NULL,
                "Quantity" integer NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "FK_CartItems_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_CartItems_RewardItems_RewardItemId" FOREIGN KEY ("RewardItemId") REFERENCES "RewardItems" ("Id") ON DELETE CASCADE
            );
            CREATE TABLE IF NOT EXISTS "RewardPurchases" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" text NOT NULL,
                "TotalPoints" integer NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "FK_RewardPurchases_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
            );
            CREATE TABLE IF NOT EXISTS "RewardPurchaseLines" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "RewardPurchaseId" integer NOT NULL,
                "RewardItemId" integer NULL,
                "ItemName" character varying(140) NOT NULL,
                "ItemDescription" character varying(600) NOT NULL,
                "ImageUrl" text NOT NULL,
                "UnitPricePoints" integer NOT NULL,
                "Quantity" integer NOT NULL,
                CONSTRAINT "FK_RewardPurchaseLines_RewardPurchases_RewardPurchaseId" FOREIGN KEY ("RewardPurchaseId") REFERENCES "RewardPurchases" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_RewardPurchaseLines_RewardItems_RewardItemId" FOREIGN KEY ("RewardItemId") REFERENCES "RewardItems" ("Id") ON DELETE SET NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_CartItems_UserId_RewardItemId" ON "CartItems" ("UserId", "RewardItemId");
            CREATE INDEX IF NOT EXISTS "IX_CartItems_RewardItemId" ON "CartItems" ("RewardItemId");
            CREATE INDEX IF NOT EXISTS "IX_RewardPurchases_UserId_CreatedAtUtc" ON "RewardPurchases" ("UserId", "CreatedAtUtc");
            CREATE INDEX IF NOT EXISTS "IX_RewardPurchaseLines_RewardPurchaseId" ON "RewardPurchaseLines" ("RewardPurchaseId");
            CREATE INDEX IF NOT EXISTS "IX_RewardPurchaseLines_RewardItemId" ON "RewardPurchaseLines" ("RewardItemId");
            """);
    }
}
